# Generated by Django 5.2.7 on 2026-03-14 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='alert_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='camera_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_no', models.BigIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='emergency_notification_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='notification_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QR_code_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeIN', models.TimeField()),
                ('timeOUT', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='chat_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromid', to=settings.AUTH_USER_MODEL)),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='emergency_notification_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('EMERGENCY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.emergency_notification_table')),
            ],
        ),
        migrations.CreateModel(
            name='RaggingEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(max_length=10)),
                ('video', models.FileField(upload_to='videos/')),
                ('audio', models.FileField(upload_to='audio/')),
                ('verified', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('CAMERA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.camera_table')),
            ],
        ),
        migrations.CreateModel(
            name='ragging_notification_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('RAGGING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.raggingevidence')),
            ],
        ),
        migrations.CreateModel(
            name='security_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dangerous_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('details', models.CharField(max_length=500)),
                ('SECURITY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.security_table')),
            ],
        ),
        migrations.CreateModel(
            name='suspicious_activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('status', models.CharField(default='notification', max_length=100)),
                ('CAMERA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.camera_table')),
            ],
        ),
        migrations.CreateModel(
            name='unknown_person_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('type', models.CharField(max_length=100)),
                ('camera_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.camera_table')),
                ('dangerous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.dangerous_person')),
            ],
        ),
        migrations.CreateModel(
            name='danger_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('DANGER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.unknown_person_table')),
            ],
        ),
        migrations.CreateModel(
            name='User_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='schedule_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeIN', models.TimeField()),
                ('timeOUT', models.TimeField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
            ],
        ),
        migrations.AddField(
            model_name='emergency_notification_table',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table'),
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='visitor_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('timeIN', models.TimeField()),
                ('timeOUT', models.TimeField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='RaggingInvolvedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('EVIDENCE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.raggingevidence')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
            ],
            options={
                'unique_together': {('STUDENT', 'EVIDENCE')},
            },
        ),
    ]
